
#server port configuration
server:
  port: 8082

#spring configuration
spring:
  application:
    name: Hotel-Service

  config:
    import: optional:configserver:http://localhost:9091

#database configuration
  datasource:
    url: jdbc:postgresql://localhost:3307/microservices
    username: postgres
    password: iamYash@22

#jpa configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


##eureka configuration
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#     defaultZone: http://localhost:8761/eureka/
