
#server port configuration
server:
  port: 9091

#spring configuration
spring:
  application:
    name: CONFIG-SERVER

#git config configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1yashsharma1/Hotel-Review-Portal-Microservices-Configurations
          clone-on-start: true
